### ISSUE TITLE
Rapportive URL changed?

### ISSUE THREAD

**Issue by MIsabelZM** [the4dpatrick/find-any-email#7]
I have been using this gem for a couple months. The day before yesterday it just stop working. 
Here it's the error:
`rescue in request': SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (HTTPI::SSLError)´

I guess that Rapportive URL changed because it looks like this one('https://rapportive.com/login_status?user_email=' + email) is not working anymore.

**Comment by philipreichen** [comment]
Any updates on getting this script running again? I'm pretty new to coding, and wanted to exactly build this. Would be great to see this work again.

**Comment by chamnap** [comment]
any update?

**Comment by chrisjhoughton** [comment]
Doesn't look there's been any progress here for a while. I haven't looked around hugely, but FullContact appear to offer a decent (pay for) alternative: https://www.fullcontact.com/developer/

**Comment by the4dpatrick** [comment]
I am willing to merge any pull requests, but I am not actively maintaining this project. As Chris mentioned, FullContact is a good alternative. That’s what I’m using on directcontact.herokuapp.com <http://directcontact.herokuapp.com/> as well.

**Comment by shrav** [comment]
You can also try out clearbit.com created by @maccman

**Comment by chamnap** [comment]
Hmm, FullContact has not quite good data as rapportive. Mostly found in rapportive, but not in FullContact.

**Comment by grinono** [comment]
I used the same tools but then not the bulk version

https://chrome.google.com/webstore/detail/find-any-email-on-linkedi/fekiadmepikilfpklicpiedpggbflnmc?hl=en-US&authuser=2

**Comment by the4dpatrick** [comment]
There are no current plans to update this script
